### PR TITLE
Some little adjustments

### PR DESCRIPTION
**Pull request by rene-schoene**
- Silence which.
- Print terminal names for print-ast.

### CODE REVIEW

**Comment by christoff-buerger** [comment]
Why has `which` to be silenced in _Bash_? It should never print on  `stderr` except in case of an error (I just tried in _macOs_ and _Ubuntu_). I prefer not to silence errors.

Regarding the printing of terminals: it should also be added to `(racr-meta testing)` to keep it up-to-date and consistent.

Please pull again with these changes. Thanks!

**Comment by rene-schoene** [comment]
Not silencing screws up the output (only purpose of which is to get the return code):

```bash
$ ./install-libraries.bash -h
Usage: -s Scheme system (optional multi-parameter). Permitted values:
which: no petite in (/home/rschoene/programs/idea/bin:/usr/local/texlive/2016/bin/x86_64-linux:/home/rschoene/.local/bin:/home/rschoene/bin:/home/rschoene/workspaces/bash:/opt/grgen/bin:/opt/larceny-0.98-bin-native-ia32-linux86/:/usr/lib64/qt-3.3/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin)
which: no sagittarius in (/home/rschoene/programs/idea/bin:/usr/local/texlive/2016/bin/x86_64-linux:/home/rschoene/.local/bin:/home/rschoene/bin:/home/rschoene/workspaces/bash:/opt/grgen/bin:/opt/larceny-0.98-bin-native-ia32-linux86/:/usr/lib64/qt-3.3/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin)
which: no IronScheme.Console-v4.exe in (/home/rschoene/programs/idea/bin:/usr/local/texlive/2016/bin/x86_64-linux:/home/rschoene/.local/bin:/home/rschoene/bin:/home/rschoene/workspaces/bash:/opt/grgen/bin:/opt/larceny-0.98-bin-native-ia32-linux86/:/usr/lib64/qt-3.3/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin)
             guile
             racket
             larceny
          If no Scheme system is selected, the selected RACR libraries
          are installed for all available systems.
...
```

**Comment by christoff-buerger** [comment]
I cannot reproduce the garbage output with either, _Bash 3.2.57_ on _macOs 10.12.3_ nor _Bash 4.4.5_ on _Ubuntu 16.04.1 LTS_. Which version of _Bash_ are you using?

Just to clarify, `stderr` is not garbage; I do not like to discard error messages since otherwise debugging the scripts is a nightmare, even with `set -e` and `set -o pipefail` (they are not helping for commands executed within `if` conditions). I think that in _Bash_, `which` should write to `stderr` only in case it is called with unknown arguments.

**Comment by christoff-buerger** [comment]
The printing of terminal names has been added (cf. issue #74 and commit 3c4124c0dcad75138118dbaeddf8dfeac4421800).

**Comment by rene-schoene** [comment]
fyi: *Bash 4.3.42(1)* on *Fedora (22 and 24)* seems to always print the path on failure.

**Comment by christoff-buerger** [comment]
`list-scheme-systems.bash` now checks for installed _R6RS Scheme_ systems using `command -v`, essentially avoiding operating system dependent behaviour (cf. issue #75 and commit 130e467028ef272867b7e351b379e4bf746b5f7e).

**Pull request closed without merging**
